name: 'Hello World Docker Action'
description: 'Greet someone and tell the time'
inputs:
  who-to-greet:
    description: 'The name of the person to greet'
    required: false
    default: 'World'
outputs:
  current-time:
    description: 'The current time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
