name: Reuse other workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "@marcomirabile"

  use-output:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "Current time: ${{ needs.call-workflow.outputs.current-time }}"

      
